name: CI for HTML Docker App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build frontend Docker image
      run: docker build -t my-html-app .

    - name: Build backend Docker image
      run: docker build -t my-backend-app ./backend

    - name: Run Docker containers
      run: |
        docker run -d -p 8080:80 my-html-app
        docker run -d -p 3000:3000 my-backend-app

    - name: Test HTTP Response for Frontend
      run: |
        sleep 5
        curl -f http://localhost:8080 | grep "Welcome"

    - name: Test Backend Response
      run: |
        sleep 5
        curl -f http://localhost:3000 | grep "Hello from the backend"
        
    - name: Run backend tests
      run: |
       docker run -d -p 3000:3000 my-backend-app
       sleep 5
       curl -f http://localhost:3000/test | grep "Test passed"
